### ISSUE TITLE
Dist file labeled es5 but uses es6 syntax

### ISSUE THREAD

**Issue by eshtadc** [clampy-js/clampy#1]
Great work continuing clamp-js. The `dist` folder provides `clampy.es5.js` which implies it is transpiled and safe to use in older browsers. The syntax in that file, however, seems to be es6 syntax. It utilizes `class`, `let`, etc. This prevents the usage of the library in IE11, etc.

**Comment by alexandremoore** [comment]
@eshtadc this should be fixed in 1.0.7.

**Comment by eshtadc** [comment]
Thanks so much @alexandremoore. I updated and confirmed that this is resolved and now works seemlessly with IE11.
